### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by Gawril** [ROMVoid95/GalacticTweaks#5]
## Issue Report (Not for Crashes - Please use Crash Report template for crashes)
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ #### Important:
 - If you decide to delete this template entirely, your issue will be closed. 
 - If you do not provide relevant information when reporting an issue (for example experiencing a bug or glitch and not providing your  latest.log or relevant log) this issue will be closed.
### Please use [This Haste Server](https://haste.romvoid.dev) to paste ANY logs as these are set to never expire. ]

[ #### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. 
If you are using an unofficial version of GalacticTweaks please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate. ]

#### Important Versions Info (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2847
- GalacticTweaks: 0.2.2-hotfix
- Galacticraft: 1.12.2-4.0.2.280
- Using a server (no): 
  - If yes, are any Server API's used, what version? (ex: Sponge): 
- List any Galacticraft Addons w/ versions:
 - Addons: Extra Planets 1.12.2-0.6.4

#### Your most recent log file where the issue was present: 

[ https://haste.romvoid.dev/ogetakizic.sql ]

**Comment by ROMVoid95** [comment]
Thanks for the report! it was missing a check for  the config option. Also it only moves the planets in Sol, does not include other  solar systems  added by EP
